security:
  jwt:
    secret-key: 'adonaaranhasubiupelaparedeveioachuvaforteeaderrubouadonaaranhasubiupelaparedeveioachuvaforteeaderrubouadonaaranhasubiupelaparedeveioachuvaforteeaderrubou'
    token-prefix: 'Bearer '
    token-expiration: 60

spring:
  application:
    name: nexus-hub-application
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushub
    username: nexushub-app
    password: nexushub-app
    driver-class-name: org.postgresql.Driver
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialetc: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    subject-dao:
      insert:
        subject: >
          INSERT INTO nexushub_platform.subject(id, name , difficulty, color) VALUES (?, ?, ?, ?::nexushub_platform.subject_color)
      update:
        subject: >
          UPDATE nexushub_platform.subject SET name=?, difficulty=?, color=?::nexushub_platform.subject_color WHERE id=?
      delete:
        subject-by-id: >
          DELETE FROM nexushub_platform.subject WHERE id=?
      exists:
        subject-by-id: >
          SELECT EXISTS(SELECT 1 FROM nexushub_platform.subject WHERE id=?)
      select:
        subject-by-id: >
          SELECT * FROM nexushub_platform.subject WHERE id=?
        subject-all: >
          SELECT * FROM nexushub_platform.subject
        subject-by-user-id: >
          SELECT * FROM nexushub_platform.subject WHERE owner_id=?
    application-user:
      insert:
        application-user: >
          INSERT INTO nexushub_platform.application_user(id, name, username, password, 
          is_account_non_expired, is_account_nonLocked, is_credentials_non_expired, is_enabled) 
          VALUES (?, ?, ?, ?, ?, ?, ?, ?)

      select:
        application-user-by-username: >
          SELECT * FROM nexushub_platform.application_user WHERE username=?
        application-user-by-id: >
          SELECT * FROM nexushub_platform.application_user WHERE id=?
      


